export const USER = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    ADD_RESERVATION: "ADD_RESERVATION",
    REMOVE_RESERVATION: "REMOVE_RESERVATION"
};

export const CATEGORY = {
    GET_CATEGORIES: "GET_CATEGORIES",
    ADD_CATEGORY: "ADD_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY"
};

export const PRODUCT = {
    GET_PRODUCTS: "GET_PRODUCTS",
    ADD_PRODUCT: "ADD_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    SET_CURRENT: "SET_PRODUCT",
    CLEAR_CURRENT: "CLEAR_CURRENT"
};

export const RESTAURANT = {
    GET_RESTAURANT: "GET_RESTAURANT",
    ADD_RESTAURANT: "ADD_RESTAURANT",
    UPDATE_RESTAURANT: "UPDATE_RESTAURANT",
    DELETE_RESTAURANT: "DELETE_RESTAURANT",
    SET_CURRENT: "SET_CURRENT",
    CLEAR_CURRENT: "CLEAR_CURRENT"
};